% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Feb-2019 18:10:32
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
saveVarsMat = load('problema1.mat');

A = saveVarsMat.A; % <1x1 sym> unsupported class

a = saveVarsMat.a; % <1x1 sym> unsupported class

ans = saveVarsMat.ans; % <1x1 sym> unsupported class

x = saveVarsMat.x; % <1x1 sym> unsupported class

clear saveVarsMat;
