% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Feb-2019 18:14:22
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
saveVarsMat = load('problema4.mat');

A = saveVarsMat.A; % <1x1 sym> unsupported class

Solx = saveVarsMat.Solx; % <1x1 sym> unsupported class

Soly = saveVarsMat.Soly; % <1x1 sym> unsupported class

a = saveVarsMat.a; % <1x1 sym> unsupported class

ans = saveVarsMat.ans; % <1x1 sym> unsupported class

b = saveVarsMat.b; % <1x1 sym> unsupported class

c = saveVarsMat.c; % <1x1 sym> unsupported class

eqs = saveVarsMat.eqs; % <1x1 sym> unsupported class

variables = saveVarsMat.variables; % <1x1 sym> unsupported class

x = saveVarsMat.x; % <1x1 sym> unsupported class

y = saveVarsMat.y; % <1x1 sym> unsupported class

y1 = saveVarsMat.y1; % <1x1 sym> unsupported class

y2 = saveVarsMat.y2; % <1x1 sym> unsupported class

clear saveVarsMat;
